/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package emailidentity

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/sesv2"

	svcapitypes "github.com/crossplane/provider-aws/apis/sesv2/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateGetEmailIdentityInput returns input for read
// operation.
func GenerateGetEmailIdentityInput(cr *svcapitypes.EmailIdentity) *svcsdk.GetEmailIdentityInput {
	res := &svcsdk.GetEmailIdentityInput{}

	if cr.Spec.ForProvider.EmailIdentity != nil {
		res.SetEmailIdentity(*cr.Spec.ForProvider.EmailIdentity)
	}

	return res
}

// GenerateEmailIdentity returns the current state in the form of *svcapitypes.EmailIdentity.
func GenerateEmailIdentity(resp *svcsdk.GetEmailIdentityOutput) *svcapitypes.EmailIdentity {
	cr := &svcapitypes.EmailIdentity{}

	if resp.ConfigurationSetName != nil {
		cr.Spec.ForProvider.ConfigurationSetName = resp.ConfigurationSetName
	} else {
		cr.Spec.ForProvider.ConfigurationSetName = nil
	}
	if resp.DkimAttributes != nil {
		f1 := &svcapitypes.DkimAttributes{}
		if resp.DkimAttributes.SigningAttributesOrigin != nil {
			f1.SigningAttributesOrigin = resp.DkimAttributes.SigningAttributesOrigin
		}
		if resp.DkimAttributes.SigningEnabled != nil {
			f1.SigningEnabled = resp.DkimAttributes.SigningEnabled
		}
		if resp.DkimAttributes.Status != nil {
			f1.Status = resp.DkimAttributes.Status
		}
		if resp.DkimAttributes.Tokens != nil {
			f1f3 := []*string{}
			for _, f1f3iter := range resp.DkimAttributes.Tokens {
				var f1f3elem string
				f1f3elem = *f1f3iter
				f1f3 = append(f1f3, &f1f3elem)
			}
			f1.Tokens = f1f3
		}
		cr.Status.AtProvider.DkimAttributes = f1
	} else {
		cr.Status.AtProvider.DkimAttributes = nil
	}
	if resp.IdentityType != nil {
		cr.Status.AtProvider.IdentityType = resp.IdentityType
	} else {
		cr.Status.AtProvider.IdentityType = nil
	}
	if resp.Tags != nil {
		f6 := []*svcapitypes.Tag{}
		for _, f6iter := range resp.Tags {
			f6elem := &svcapitypes.Tag{}
			if f6iter.Key != nil {
				f6elem.Key = f6iter.Key
			}
			if f6iter.Value != nil {
				f6elem.Value = f6iter.Value
			}
			f6 = append(f6, f6elem)
		}
		cr.Spec.ForProvider.Tags = f6
	} else {
		cr.Spec.ForProvider.Tags = nil
	}
	if resp.VerifiedForSendingStatus != nil {
		cr.Status.AtProvider.VerifiedForSendingStatus = resp.VerifiedForSendingStatus
	} else {
		cr.Status.AtProvider.VerifiedForSendingStatus = nil
	}

	return cr
}

// GenerateCreateEmailIdentityInput returns a create input.
func GenerateCreateEmailIdentityInput(cr *svcapitypes.EmailIdentity) *svcsdk.CreateEmailIdentityInput {
	res := &svcsdk.CreateEmailIdentityInput{}

	if cr.Spec.ForProvider.ConfigurationSetName != nil {
		res.SetConfigurationSetName(*cr.Spec.ForProvider.ConfigurationSetName)
	}
	if cr.Spec.ForProvider.DkimSigningAttributes != nil {
		f1 := &svcsdk.DkimSigningAttributes{}
		if cr.Spec.ForProvider.DkimSigningAttributes.DomainSigningPrivateKey != nil {
			f1.SetDomainSigningPrivateKey(*cr.Spec.ForProvider.DkimSigningAttributes.DomainSigningPrivateKey)
		}
		if cr.Spec.ForProvider.DkimSigningAttributes.DomainSigningSelector != nil {
			f1.SetDomainSigningSelector(*cr.Spec.ForProvider.DkimSigningAttributes.DomainSigningSelector)
		}
		res.SetDkimSigningAttributes(f1)
	}
	if cr.Spec.ForProvider.EmailIdentity != nil {
		res.SetEmailIdentity(*cr.Spec.ForProvider.EmailIdentity)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f3 := []*svcsdk.Tag{}
		for _, f3iter := range cr.Spec.ForProvider.Tags {
			f3elem := &svcsdk.Tag{}
			if f3iter.Key != nil {
				f3elem.SetKey(*f3iter.Key)
			}
			if f3iter.Value != nil {
				f3elem.SetValue(*f3iter.Value)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTags(f3)
	}

	return res
}

// GenerateDeleteEmailIdentityInput returns a deletion input.
func GenerateDeleteEmailIdentityInput(cr *svcapitypes.EmailIdentity) *svcsdk.DeleteEmailIdentityInput {
	res := &svcsdk.DeleteEmailIdentityInput{}

	if cr.Spec.ForProvider.EmailIdentity != nil {
		res.SetEmailIdentity(*cr.Spec.ForProvider.EmailIdentity)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "NotFoundException"
}
